### ISSUE TITLE
Error: Unexpected value 'GoogleChart' declared by the module

### ISSUE THREAD

**Issue by MorlaRamakrishna** [vimalavinisha/angular2-google-chart#39]
I have imported 'GoogleChart' in Module and added it to declarations array, but still getting this error.

**Comment by vimalavinisha** [comment]
Hi please ref the below link for the installation process
https://github.com/vimalavinisha/angular2-google-chart/issues/25

I will update the readme soon

**Comment by MorlaRamakrishna** [comment]
Hi VimalaVinisha,

I have followed the same process to install, but getting the same error.

**Comment by MorlaRamakrishna** [comment]
![image](https://cloud.githubusercontent.com/assets/26458893/26100228/edb43a60-3a4a-11e7-87ca-750341b873a9.png)

**Comment by vimalavinisha** [comment]
Did you give the path match in the system.config.js if SystemJS used like
var map = {
    'angular2-google-chart': 'node_modules/angular2-google-chart'

}
var packages = {
    'angular2-google-chart': {defaultExtension: 'js'}
}

**Comment by MorlaRamakrishna** [comment]
I am using web pack it will take care of that

**Comment by ilanle** [comment]
Having the same issue, this installation doesn't work well with webpack

**Comment by pawelec** [comment]
Same problem.

**Comment by vimalavinisha** [comment]
Please check whether you have given the correct npm module path

**Comment by Gicus** [comment]
The same issue. Probably, angular2-google-chart is not compatible with angular 4.1.3 I think we can use it only with 4.0.2 Please, can you confirm me, if I'm right? `Uncaught Error: Unexpected value 'GoogleChart' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:56146:34) [<root>]
    at http://localhost:4200/vendor.bundle.js:69148:40 [<root>]
    at Array.forEach (native) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:69130:54) [<root>]
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:80236:66) [<root>]
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:80195:52) [<root>]
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:80157:23) [<root>]
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5218:25) [<root>]
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5204:21) [<root>]
    at Object.342 (http://localhost:4200/main.bundle.js:1211:124) [<root>]`

**Comment by wraith7** [comment]
Same here. I am using 4.1.3 and I got same error with @Gicus .
While I was running npm install I got following warnings.

`└─┬ angular2-google-chart@2.2.3
  ├── @angular/common@4.0.2
  ├── UNMET PEER DEPENDENCY @angular/compiler@4.0.2
  ├── UNMET PEER DEPENDENCY @angular/core@4.0.2
  ├── UNMET PEER DEPENDENCY @angular/platform-browser@4.0.2
  ├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.0.2
  ├── @angular/upgrade@4.0.2
  ├─┬ systemjs@0.19.27
  │ └── when@3.7.8
  └── zone.js@0.8.4

npm WARN @angular/upgrade@4.0.2 requires a peer of @angular/core@4.0.2 but none was installed.
npm WARN @angular/upgrade@4.0.2 requires a peer of @angular/compiler@4.0.2 but none was installed.
npm WARN @angular/upgrade@4.0.2 requires a peer of @angular/platform-browser@4.0.2 but none was installed.
npm WARN @angular/upgrade@4.0.2 requires a peer of @angular/platform-browser-dynamic@4.0.2 but none was installed.`

**Comment by Gicus** [comment]
@wraith7  Did you find a solution?

**Comment by vimalavinisha** [comment]
@Gicus , @wraith7 

Now I updated this package to angualr - 4.1.3
Please take a new version of lib and check
Let me know whether this issue has been fixed or not

**Comment by lvr123321** [comment]
@vimalavinisha 

I got the last version and it still gives the same error, but I'm using the angular - 4.2.3

command: ng build --aot --progress --verbose
![image](https://user-images.githubusercontent.com/13267260/27310985-3d2376fc-5534-11e7-85f7-a1995cdd0273.png)

dependencies:
![image](https://user-images.githubusercontent.com/13267260/27310997-5714113e-5534-11e7-9dfd-1ea74c864f73.png)

**Comment by ccdle12** [comment]
Same problem here... It was working previously and then I cloned my repo with this code again and now it doesn't work...

**Comment by lvr123321** [comment]
I solved this problem by setting the path in the tsconfig.json file that is used by angular-cli

![image](https://user-images.githubusercontent.com/13267260/27361669-6a011816-55ff-11e7-8966-fe09caff0af0.png)




You can see the fix here
angular/angular-cli#4647 (comment)

**Comment by ccdle12** [comment]
@lvr123321 

Thanks, this solution worked for me

**Comment by ahaan729** [comment]
The error comes everytime there is a mismatch between angular's version (@4.2.4) and angular2-google-chart's version..
Please update the package.json as in #43

**Comment by sagarthecook** [comment]
same here ,i'm using angular version 4.1.3 but still getting 
**Uncaught Error: Unexpected value 'GoogleChart' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.** Error

**Comment by maliaga** [comment]
I'm using version 4.3.2 some error.

**Comment by larcheryjung** [comment]
> I solved this problem by setting the path in the tsconfig.json file that is used by angular-cli
> 
> ![image](https://user-images.githubusercontent.com/13267260/27361669-6a011816-55ff-11e7-8966-fe09caff0af0.png)
> 
> You can see the fix here
> [angular/angular-cli#4647](https://github.com/angular/angular-cli/issues/4647) (comment)

This solve my problem too, I was using Angular 4.4.3, and I tried alot of things
```
    "paths": {   
      "@angular/common": ["../node_modules/@angular/common"],
      "@angular/compiler": ["../node_modules/@angular/compiler"],
      "@angular/core": ["../node_modules/@angular/core"],
      "@angular/forms": ["../node_modules/@angular/forms"],
      "@angular/router": ["../node_modules/@angular/router"],
      "@angular/platform-browser": ["../node_modules/@angular/platform-browser"],
      "@angular/platform-browser-dynamic": ["../node_modules/@angular/platform-browser-dynamic"],
      "@angular/http": ["../node_modules/@angular/http"]
    }
```
do not leave any trailing comma
