### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by shaozi** [vimalavinisha/angular2-google-chart#69]
```
ERROR in ./node_modules/angular2-google-chart/directives/angular2-google-chart.directive.ts
Module build failed: Error: /Users/jingshaochen/Documents/pgm/hashmon/node_modules/angular2-google-chart/directives/angular2-google-chart.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/jingshaochen/Documents/pgm/hashmon/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/Users/jingshaochen/Documents/pgm/hashmon/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 13:40-115
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by mactechlabs** [comment]
having the same issue here

**Comment by sasin07** [comment]
I also have same issue here

**Comment by nadavlev** [comment]
Same Error

**Comment by shmulikmak** [comment]
same error
