### ISSUE TITLE
node_modules\angular2-google-chart\directives\angular2-google-chart.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by kalptechy** [vimalavinisha/angular2-google-chart#71]
ERROR in ./node_modules/angular2-google-chart/directives/angular2-google-chart.directive.ts
Module build failed: Error: C:\AngularProject\xxxxx\frontend\node_modules\angular2-google-chart\directives\angular2-google-chart.directive.ts is missing from
the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\AngularProject\xxxxx\frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\AngularProject\sbncoin\frontend\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 58:40-115
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by Fl4v10** [comment]
I had the same error, so, please, did you find out a solution????

**Comment by siddarthaboddu** [comment]
I am also facing the same problem.

**Comment by jakeclarklucentmobile** [comment]
Same issue here

**Comment by debangshuk** [comment]
Facing the same issue.

**Comment by chalpat** [comment]
Same issue, any solutions?

**Comment by mannyorozco** [comment]
Added to `imports: [ GoogleChart ]` and error went away, but got warning 

`WARNING in ./node_modules/angular2-google-chart/directives/angular2-google-chart.directive.ts
System.register is not supported by webpack.` 

running A6
